language: node_js
node_js:
  - node
dist: trusty
sudo: false

branches:
  only:
  - dev

cache:
  directories:
    - node_modules

before_install:
  - openssl aes-256-cbc -K $encrypted_85ff80d04e78_key -iv $encrypted_85ff80d04e78_iv -in github_deploy_key.enc -out github_deploy_key -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key

script:
  - yarn build --production

after_success:
  - bash ./scripts/deploy-to-gh-pages.sh

notifications:
  email:
    on_success: never # default: change
    on_failure: never # default: always

